coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "tools/**"
  - "cmd/cshared"
  - "internal/locksoupasm/**"
  - "bindings/**"
  - "scripts/**"
  - "**/*_test.go"
