package itb_test

import (
	"bytes"
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"os"
	"strconv"
	"testing"

	"github.com/everanium/itb"
	"github.com/everanium/itb/aesitb"
	"github.com/everanium/itb/hashes"
	"github.com/everanium/itb/internal/aesitbasm"
	"github.com/everanium/itb/internal/forcetier"
	"github.com/everanium/itb/internal/interlock"
	"github.com/everanium/itb/triple"
)

// AES-ITB-128 coverage at the itb package boundary: production-vs-reference
// parity on the recorded vectors, dispatch-tier and round-constant pinning,
// fused ChainHash cascade parity on the four- and eight-lane arms, and the
// benchmark cells for the batched arm, for the Triple Ouroboros integration
// path and for the shipped AES-ITB pipeline profiles.

// --- Reference vectors: production vs the leaf reference package ---

// Production-vs-reference parity for AES-ITB-128. Every vector below was
// generated by the Python reference and is duplicated verbatim in
// aesitb/aesitb_test.go; production (itb root) and the leaf reference
// (aesitb) are checked against each other and against the recorded hex.
//
// Inputs: key = 00 11 22 .. FF; generic data = 0x00, 0x01, ... (dataLen
// bytes).

type aesitbGenericVector struct {
	dataLen      int
	seed0, seed1 uint64
	want         string
}

var aesitbParityKey = [16]byte{0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF}

func aesitbParityData(n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = byte(i)
	}
	return out
}

var aesitbGenericVectors = []aesitbGenericVector{
	{0, 0x0, 0x0, "d03e268799c14203bdb3e663165d6b23"},
	{1, 0x0, 0x0, "f2a4e404c80c84451e35cadcc7f22bb9"},
	{15, 0x0, 0x0, "95be57f5a239f3ab144382b7cd8695de"},
	{16, 0x0, 0x0, "3171e8f8165c8ff5203ac9aa371c719a"},
	{17, 0x0, 0x0, "48d3f6fcc2985cf31a074ea2c78b1d09"},
	{31, 0x0, 0x0, "064e72d014e7a41c4fc3b7d1b938f625"},
	{32, 0x0, 0x0, "e08f48e9037d3bc81d03dc0adc1b9d3b"},
	{33, 0x0, 0x0, "7370df93d8fd5e118d33484f582e1750"},
	{63, 0x0, 0x0, "c17822cc92d1a5fb712a1ea655de82ad"},
	{64, 0x0, 0x0, "81615890aab0306bf4b32bbe2d7ca1af"},
	{0, 0x1, 0x0, "787e6d0bae570d2ec58796bcbf68c172"},
	{0, 0x0, 0x1, "e9d430852929ab3d88c240ddc40f823c"},
	{5, 0x123456789abcdef, 0xfedcba9876543210, "7486079419f3f0767b579065d6cc3d93"},
	{16, 0xffffffffffffffff, 0xffffffffffffffff, "2eae20695db216506bd63f96fda12ca0"},
	{33, 0x7, 0x9, "dccfc56b263e1a2fc13052534f15092e"},
	{64, 0x8000000000000000, 0x1, "a7a8e09b329611b7aec6a97b0e75cd25"},
}

// aesitbWords16 lays a HashFunc128 (lo, hi) pair out as the 16-byte
// little-endian block the reference API returns.
func aesitbWords16(lo, hi uint64) [16]byte {
	var out [16]byte
	for i := 0; i < 8; i++ {
		out[i] = byte(lo >> (8 * i))
		out[8+i] = byte(hi >> (8 * i))
	}
	return out
}

func TestAESITBParityGeneric(t *testing.T) {
	single, _, key, err := hashes.Make128Pair(hashes.CipherAESITB128, aesitbParityKey[:])
	if err != nil {
		t.Fatalf("Make128Pair: %v", err)
	}
	if string(key) != string(aesitbParityKey[:]) {
		t.Fatalf("Make128Pair returned key %x, want %x", key, aesitbParityKey)
	}
	for _, v := range aesitbGenericVectors {
		data := aesitbParityData(v.dataLen)
		lo, hi := single(data, v.seed0, v.seed1)
		p := aesitbWords16(lo, hi)
		r := aesitb.HashGeneric(aesitbParityKey, data, v.seed0, v.seed1)
		if p != r {
			t.Errorf("len=%d seeds=(%#x,%#x): production %x != reference %x", v.dataLen, v.seed0, v.seed1, p, r)
		}
		if got := hex.EncodeToString(p[:]); got != v.want {
			t.Errorf("len=%d seeds=(%#x,%#x): got %s want %s", v.dataLen, v.seed0, v.seed1, got, v.want)
		}
	}
}

func TestAESITBParityBatch(t *testing.T) {
	single, batched, _, err := hashes.Make128Pair(hashes.CipherAESITB128, aesitbParityKey[:])
	if err != nil {
		t.Fatalf("Make128Pair: %v", err)
	}
	if batched == nil {
		t.Fatal("Make128Pair returned a nil batched arm for aesitb128")
	}
	// Four lanes with distinct lengths (empty, tail-only, full block,
	// multi-block) and distinct seeds, all drawn from the generic vectors.
	picks := []int{0, 12, 13, 15}
	var lanes [4][]byte
	var seeds [4][2]uint64
	for i, p := range picks {
		v := aesitbGenericVectors[p]
		lanes[i] = aesitbParityData(v.dataLen)
		seeds[i] = [2]uint64{v.seed0, v.seed1}
	}
	out := batched(&lanes, seeds)
	for i, p := range picks {
		v := aesitbGenericVectors[p]
		lo, hi := single(lanes[i], seeds[i][0], seeds[i][1])
		if out[i][0] != lo || out[i][1] != hi {
			t.Errorf("lane %d: batched (%#x,%#x) != single (%#x,%#x)", i, out[i][0], out[i][1], lo, hi)
		}
		b := aesitbWords16(out[i][0], out[i][1])
		r := aesitb.HashGeneric(aesitbParityKey, lanes[i], seeds[i][0], seeds[i][1])
		if b != r {
			t.Errorf("lane %d: batched %x != reference %x", i, b, r)
		}
		if got := hex.EncodeToString(b[:]); got != v.want {
			t.Errorf("lane %d: got %s want %s", i, got, v.want)
		}
	}
}

// --- Batched arm benchmark ---

// BenchmarkAESITBBatchedArm compares the aesitb128 batched arm (4-lane
// chain-absorb reference) against four calls of the single arm on the
// same inputs, per per-pixel shape. Bytes/op = 4 × shape.
func BenchmarkAESITBBatchedArm(b *testing.B) {
	single, batched, _, err := hashes.Make128Pair(hashes.CipherAESITB128, aesitbParityKey[:])
	if err != nil {
		b.Fatal(err)
	}
	for _, n := range []int{13, 20, 36, 68} {
		var lanes [4][]byte
		for i := range lanes {
			lanes[i] = aesitbParityData(n)
		}
		seeds := [4][2]uint64{{1, 2}, {3, 4}, {5, 6}, {7, 8}}
		b.Run(fmt.Sprintf("single4/shape%d", n), func(b *testing.B) {
			b.SetBytes(int64(4 * n))
			b.ReportAllocs()
			var sink uint64
			for i := 0; i < b.N; i++ {
				for l := 0; l < 4; l++ {
					lo, _ := single(lanes[l], seeds[l][0]^uint64(i), seeds[l][1])
					sink ^= lo
				}
			}
			_ = sink
		})
		b.Run(fmt.Sprintf("batched/shape%d", n), func(b *testing.B) {
			b.SetBytes(int64(4 * n))
			b.ReportAllocs()
			var sink uint64
			for i := 0; i < b.N; i++ {
				seeds[0][0] = uint64(i)
				out := batched(&lanes, seeds)
				sink ^= out[0][0]
			}
			_ = sink
		})
	}
}

// --- Dispatch tiers and round constants ---

// tierFlags is a snapshot of the aesitbasm dispatch flags — the
// fused-cascade family.
type tierFlags struct {
	fzmm, fymm, fvex, faesni, farm bool
}

func readTierFlags() tierFlags {
	return tierFlags{
		aesitbasm.FusedHasVAESAVX512, aesitbasm.FusedHasVAESAVX2,
		aesitbasm.FusedHasAVXAESNI, aesitbasm.FusedHasAESNI, aesitbasm.FusedHasARMAES,
	}
}

func (f tierFlags) apply() {
	aesitbasm.FusedHasVAESAVX512, aesitbasm.FusedHasVAESAVX2 = f.fzmm, f.fymm
	aesitbasm.FusedHasAVXAESNI, aesitbasm.FusedHasAESNI, aesitbasm.FusedHasARMAES = f.fvex, f.faesni, f.farm
}

// withTierFlags installs f for the remainder of the test and registers a
// Cleanup that restores the flags the test started with, so every test
// that mutates the package-level dispatch flags leaves them as found
// regardless of how it exits.
func withTierFlags(t *testing.T, f tierFlags) {
	t.Helper()
	saved := readTierFlags()
	t.Cleanup(saved.apply)
	f.apply()
}

// TestAESITBCrossTierRoundTrip encrypts under one dispatch tier and
// decrypts under the other, both directions, on the AES-ITB Single
// Message and Streaming AEAD profiles. The per-pixel hash is the same
// function on every tier, so wire produced by the scalar reference must
// decrypt under the SIMD tier and vice versa.
func TestAESITBCrossTierRoundTrip(t *testing.T) {
	auto := readTierFlags()
	if auto == (tierFlags{}) {
		t.Skip("no assembly tier on this host; scalar is the only path")
	}
	scalar := tierFlags{}

	plain := make([]byte, 300_000)
	rand.Read(plain)

	for _, tc := range []struct {
		profile   string
		streaming bool
	}{
		{triple.ProfileSingleMsgAESITBNoMACV1, false},
		{triple.ProfileSingleMsgAESITBMACV1, false},
		{triple.ProfileStreamingAEADAESITBMACV1, true},
	} {
		t.Run(tc.profile, func(t *testing.T) {
			withTierFlags(t, auto)
			p, _, err := triple.Init(tc.profile, triple.Opts{})
			if err != nil {
				t.Fatalf("Init: %v", err)
			}
			defer p.Close()
			enc := func(in []byte) ([]byte, error) {
				if tc.streaming {
					return p.EncryptStreamBytes(in)
				}
				return p.EncryptMessage(in)
			}
			dec := func(in []byte) ([]byte, error) {
				if tc.streaming {
					return p.DecryptStreamBytes(in)
				}
				return p.DecryptMessage(in)
			}

			scalar.apply()
			wireScalar, err := enc(plain)
			if err != nil {
				t.Fatalf("scalar encrypt: %v", err)
			}
			auto.apply()
			wireAuto, err := enc(plain)
			if err != nil {
				t.Fatalf("auto-tier encrypt: %v", err)
			}

			got, err := dec(wireScalar)
			if err != nil || !bytes.Equal(got, plain) {
				t.Fatalf("scalar wire under auto tier: err=%v match=%v", err, bytes.Equal(got, plain))
			}
			scalar.apply()
			got, err = dec(wireAuto)
			if err != nil || !bytes.Equal(got, plain) {
				t.Fatalf("auto-tier wire under scalar: err=%v match=%v", err, bytes.Equal(got, plain))
			}
		})
	}
}

// TestAESITBRoundConstantsAgree pins the kernel package's round-constant
// table to the recorded rows the reference package re-derives from sqrt(p).
func TestAESITBRoundConstantsAgree(t *testing.T) {
	want := [8]string{
		"6a09e667bb67ae853c6ef372a54ff53a",
		"510e527f9b05688c1f83d9ab5be0cd19",
		"6a09e667f3bcc908bb67ae8584caa73b",
		"3c6ef372fe94f82ba54ff53a5f1d36f1",
		"510e527fade682d19b05688c2b3e6c1f",
		"1f83d9abfb41bd6b5be0cd19137e2179",
		"cbbb9d5dc1059ed8629a292a367cd507",
		"9159015a3070dd17152fecd8f70e5939",
	}
	for i := range want {
		if got := hexOf(aesitbasm.RC[i][:]); got != want[i] {
			t.Errorf("aesitbasm.RC[%d] = %s, want %s", i, got, want[i])
		}
	}
}

func hexOf(b []byte) string {
	const digits = "0123456789abcdef"
	out := make([]byte, 0, 2*len(b))
	for _, c := range b {
		out = append(out, digits[c>>4], digits[c&15])
	}
	return string(out)
}

// --- Fused ChainHash cascade parity: four lanes ---

// Fused-cascade parity: a Seed128 with the fused hooks attached must
// return exactly what the same seed returns through the sequential
// per-round loop, on every per-pixel shape and every shipped KeyBits
// (8 / 16 / 32 components), and both must agree with the cascade
// composed from the leaf reference package's HashGeneric.

var fusedShapes = []int{13, 20, 36, 68}
var fusedKeyBits = []int{512, 1024, 2048}

func newAESITBSeedPair(t *testing.T, bits int) (fused, seq *itb.Seed128) {
	t.Helper()
	if forcetier.ChainHashSeq() {
		t.Skip("ITB_FORCE_CHAINHASH_SEQ set: the fused hooks stay nil by design")
	}
	single, batched, _, err := hashes.Make128Pair(hashes.CipherAESITB128, aesitbParityKey[:])
	if err != nil {
		t.Fatal(err)
	}
	fused, _, err = hashes.NewSeed128(hashes.CipherAESITB128, bits, aesitbParityKey[:])
	if err != nil {
		t.Fatal(err)
	}
	if fused.FusedChain == nil || fused.BatchFusedChain == nil {
		t.Fatal("NewSeed128 left the fused hooks nil")
	}
	seq = &itb.Seed128{Components: append([]uint64(nil), fused.Components...), Hash: single, BatchHash: batched}
	return fused, seq
}

func referenceCascade(comps []uint64, data []byte) (uint64, uint64) {
	out := aesitb.HashGeneric(aesitbParityKey, data, comps[0], comps[1])
	lo, hi := binary.LittleEndian.Uint64(out[:8]), binary.LittleEndian.Uint64(out[8:])
	for i := 2; i < len(comps); i += 2 {
		out = aesitb.HashGeneric(aesitbParityKey, data, comps[i]^lo, comps[i+1]^hi)
		lo, hi = binary.LittleEndian.Uint64(out[:8]), binary.LittleEndian.Uint64(out[8:])
	}
	return lo, hi
}

func TestAESITBFusedChainHashParity(t *testing.T) {
	for _, bits := range fusedKeyBits {
		fused, seq := newAESITBSeedPair(t, bits)
		for _, n := range fusedShapes {
			for iter := 0; iter < 64; iter++ {
				data := make([]byte, n)
				rand.Read(data)
				fLo, fHi := fused.ChainHash128(data)
				sLo, sHi := seq.ChainHash128(data)
				rLo, rHi := referenceCascade(fused.Components, data)
				if fLo != sLo || fHi != sHi {
					t.Fatalf("bits=%d n=%d: fused (%x,%x) != sequential (%x,%x)", bits, n, fLo, fHi, sLo, sHi)
				}
				if fLo != rLo || fHi != rHi {
					t.Fatalf("bits=%d n=%d: fused (%x,%x) != reference cascade (%x,%x)", bits, n, fLo, fHi, rLo, rHi)
				}
			}
		}
		// Non-shape lengths must decline the fused path and still agree.
		for _, n := range []int{0, 1, 17, 33, 65} {
			data := make([]byte, n)
			rand.Read(data)
			fLo, fHi := fused.ChainHash128(data)
			sLo, sHi := seq.ChainHash128(data)
			if fLo != sLo || fHi != sHi {
				t.Fatalf("bits=%d non-shape n=%d: fused hook diverged from sequential", bits, n)
			}
		}
	}
}

func TestAESITBFusedBatchChainHashParity(t *testing.T) {
	for _, bits := range fusedKeyBits {
		fused, seq := newAESITBSeedPair(t, bits)
		for _, n := range fusedShapes {
			for iter := 0; iter < 64; iter++ {
				var lanes [4][]byte
				for l := range lanes {
					lanes[l] = make([]byte, n)
					rand.Read(lanes[l])
				}
				f := fused.BatchChainHash128(&lanes)
				s := seq.BatchChainHash128(&lanes)
				if f != s {
					t.Fatalf("bits=%d n=%d: batched fused %x != sequential %x", bits, n, f, s)
				}
				for l := 0; l < 4; l++ {
					rLo, rHi := referenceCascade(fused.Components, lanes[l])
					if f[l][0] != rLo || f[l][1] != rHi {
						t.Fatalf("bits=%d n=%d lane %d: batched fused != reference cascade", bits, n, l)
					}
				}
			}
		}
		// Mixed lane lengths decline the fused path.
		lanes := [4][]byte{make([]byte, 20), make([]byte, 20), make([]byte, 36), make([]byte, 20)}
		if fused.BatchChainHash128(&lanes) != seq.BatchChainHash128(&lanes) {
			t.Fatalf("bits=%d: mixed-length lanes diverged", bits)
		}
	}
}

// TestAESITBFusedSeqEnvToggle pins ITB_FORCE_CHAINHASH_SEQ: the factory
// returns nil evaluators when it is set, so a seed built through the
// name-keyed constructor stays sequential.
func TestAESITBFusedSeqEnvToggle(t *testing.T) {
	t.Setenv("ITB_FORCE_CHAINHASH_SEQ", "1")
	s, _, err := hashes.NewSeed128(hashes.CipherAESITB128, 512, aesitbParityKey[:])
	if err != nil {
		t.Fatal(err)
	}
	if s.FusedChain != nil || s.BatchFusedChain != nil || s.BatchFusedChain8() != nil {
		t.Fatal("fused hooks populated despite ITB_FORCE_CHAINHASH_SEQ=1")
	}
}

// TestAESITBFusedWireRoundTrip encrypts through a pipeline built with the
// sequential loop and decrypts through one built with the fused hooks,
// and vice versa, so the wire bytes are pinned equal across the two
// paths on every AES-ITB profile.
func TestAESITBFusedWireRoundTrip(t *testing.T) {
	plain := make([]byte, 200_000)
	rand.Read(plain)
	for _, tc := range []struct {
		profile   string
		streaming bool
	}{
		{triple.ProfileSingleMsgAESITBNoMACV1, false},
		{triple.ProfileSingleMsgAESITBMACV1, false},
		{triple.ProfileStreamingAEADAESITBMACV1, true},
		{triple.ProfileStreamingNoAEADAESITBV1, true},
	} {
		t.Run(tc.profile, func(t *testing.T) {
			t.Setenv("ITB_FORCE_CHAINHASH_SEQ", "1")
			pSeq, blob, err := triple.Init(tc.profile, triple.Opts{})
			t.Setenv("ITB_FORCE_CHAINHASH_SEQ", "")
			if err != nil {
				t.Fatalf("Init(seq): %v", err)
			}
			defer pSeq.Close()
			pFused, err := triple.Load(blob)
			if err != nil {
				t.Fatalf("Load(fused): %v", err)
			}
			defer pFused.Close()
			run := func(enc, dec *triple.Pipeline) {
				var wire, got []byte
				var err error
				if tc.streaming {
					wire, err = enc.EncryptStreamBytes(plain)
				} else {
					wire, err = enc.EncryptMessage(plain)
				}
				if err != nil {
					t.Fatalf("encrypt: %v", err)
				}
				if tc.streaming {
					got, err = dec.DecryptStreamBytes(wire)
				} else {
					got, err = dec.DecryptMessage(wire)
				}
				if err != nil || string(got) != string(plain) {
					t.Fatalf("decrypt: err=%v match=%v", err, string(got) == string(plain))
				}
			}
			run(pSeq, pFused)
			run(pFused, pSeq)
		})
	}
}

// --- Fused ChainHash cascade parity: eight lanes ---

// Eight-lane fused-cascade parity: on hosts whose selected tier carries
// the eight-lane ZMM arm, every shipping aesitb128 constructor attaches
// the eight-lane hook, the hook agrees lane for lane with the four-lane
// path, and the wire produced through the eight-pixel stride decrypts
// through the four-pixel stride and vice versa.

// x8Hosted skips the test on hosts (or forced tiers) without the
// eight-lane arm and under ITB_FORCE_CHAINHASH_SEQ, which leaves every
// fused hook nil by design; the four-lane parity tests cover those.
func x8Hosted(t *testing.T) {
	t.Helper()
	if !aesitbasm.FusedX8Active() {
		t.Skip("eight-lane ZMM fused arm not selected on this host / tier")
	}
	if forcetier.ChainHashSeq() {
		t.Skip("ITB_FORCE_CHAINHASH_SEQ set: the fused hooks stay nil by design")
	}
}

// withX8Arm runs fn with the eight-lane arm set as given and restores
// the flag afterwards; seeds attached inside fn carry the hook exactly
// when armed is true.
func withX8Arm(t *testing.T, armed bool, fn func()) {
	t.Helper()
	saved := aesitbasm.FusedHasVAESAVX512X8
	aesitbasm.FusedHasVAESAVX512X8 = armed
	defer func() { aesitbasm.FusedHasVAESAVX512X8 = saved }()
	fn()
}

// newAESITBSeed builds a fresh aesitb128 seed through the name-keyed
// constructor every shipping constructor path runs, under an optional
// caller-supplied fixed key, and returns the key the arms are bound to.
func newAESITBSeed(t *testing.T, bits int, key []byte) (*itb.Seed128, []byte) {
	t.Helper()
	var keyArg [][]byte
	if len(key) > 0 {
		keyArg = [][]byte{key}
	}
	s, fixedKey, err := hashes.NewSeed128(hashes.CipherAESITB128, bits, keyArg...)
	if err != nil {
		t.Fatal(err)
	}
	return s, fixedKey
}

// aesitbSeedFromComponents rebuilds an aesitb128 seed from existing
// components under its fixed key through the name-keyed restore
// constructor.
func aesitbSeedFromComponents(t *testing.T, key []byte, comps []uint64) *itb.Seed128 {
	t.Helper()
	s, err := hashes.SeedFromComponents128(hashes.CipherAESITB128, key, comps...)
	if err != nil {
		t.Fatal(err)
	}
	return s
}

// TestAESITBFusedX8Attach pins the attach step: both name-keyed
// constructors carry the eight-lane hook when the arm is selected, and
// neither carries it when the arm is disarmed or the sequential loop is
// forced.
func TestAESITBFusedX8Attach(t *testing.T) {
	x8Hosted(t)
	fromHelper, key := newAESITBSeed(t, 1024, nil)
	if fromHelper.BatchFusedChain8() == nil {
		t.Fatal("NewSeed128 left the eight-lane hook nil")
	}
	fromComponents := aesitbSeedFromComponents(t, key, fromHelper.Components)
	if fromComponents.BatchFusedChain8() == nil {
		t.Fatal("SeedFromComponents128 left the eight-lane hook nil")
	}

	withX8Arm(t, false, func() {
		s := aesitbSeedFromComponents(t, key, fromHelper.Components)
		if s.BatchFusedChain == nil || s.BatchFusedChain8() != nil {
			t.Fatal("disarmed eight-lane arm: want four-lane hook only")
		}
	})
	t.Setenv("ITB_FORCE_CHAINHASH_SEQ", "1")
	seq := aesitbSeedFromComponents(t, key, fromHelper.Components)
	if seq.BatchFusedChain != nil || seq.BatchFusedChain8() != nil {
		t.Fatal("ITB_FORCE_CHAINHASH_SEQ=1: fused hooks populated")
	}
}

// TestAESITBFusedX8HookParity pins the eight-lane hook to the four-lane
// batched cascade over the lane halves, on every nonce-buf shape and
// every shipped KeyBits, and checks that non-shape lengths decline.
func TestAESITBFusedX8HookParity(t *testing.T) {
	x8Hosted(t)
	for _, bits := range fusedKeyBits {
		s, _ := newAESITBSeed(t, bits, aesitbParityKey[:])
		hook := s.BatchFusedChain8()
		if hook == nil {
			t.Fatalf("bits=%d: eight-lane hook nil", bits)
		}
		for _, n := range []int{20, 36, 68} {
			for iter := 0; iter < 64; iter++ {
				var lanes [8][]byte
				for l := range lanes {
					lanes[l] = make([]byte, n)
					rand.Read(lanes[l])
				}
				got, ok := hook(s.Components, &lanes)
				if !ok {
					t.Fatalf("bits=%d n=%d: hook declined a nonce-buf shape", bits, n)
				}
				lo := [4][]byte{lanes[0], lanes[1], lanes[2], lanes[3]}
				hi := [4][]byte{lanes[4], lanes[5], lanes[6], lanes[7]}
				wantLo, wantHi := s.BatchChainHash128(&lo), s.BatchChainHash128(&hi)
				for l := 0; l < 4; l++ {
					if got[l] != wantLo[l] || got[4+l] != wantHi[l] {
						t.Fatalf("bits=%d n=%d iter %d: eight-lane hook diverged from the four-lane cascade", bits, n, iter)
					}
				}
				for l := 0; l < 8; l++ {
					rLo, rHi := referenceCascade(s.Components, lanes[l])
					if got[l][0] != rLo || got[l][1] != rHi {
						t.Fatalf("bits=%d n=%d lane %d: eight-lane hook != reference cascade", bits, n, l)
					}
				}
			}
		}
		for _, n := range []int{13, 17, 33, 65} {
			var lanes [8][]byte
			for l := range lanes {
				lanes[l] = make([]byte, n)
			}
			if _, ok := hook(s.Components, &lanes); ok {
				t.Fatalf("bits=%d: hook accepted non-shape length %d", bits, n)
			}
		}
		mixed := [8][]byte{make([]byte, 68), make([]byte, 68), make([]byte, 68), make([]byte, 68),
			make([]byte, 68), make([]byte, 68), make([]byte, 36), make([]byte, 68)}
		if _, ok := hook(s.Components, &mixed); ok {
			t.Fatalf("bits=%d: hook accepted mixed lane lengths", bits)
		}
	}
}

// TestAESITBFusedX8WireRoundTrip encrypts through a pipeline built with
// the eight-lane arm and decrypts through one built without it (four-lane
// fused kernels, four-pixel stride), and vice versa, on every AES-ITB
// profile and every nonce width, so the wire is pinned equal across the
// two pixel strides.
func TestAESITBFusedX8WireRoundTrip(t *testing.T) {
	x8Hosted(t)
	plain := make([]byte, 300_007)
	rand.Read(plain)
	for _, nb := range []int{128, 256, 512} {
		for _, tc := range []struct {
			profile   string
			streaming bool
		}{
			{triple.ProfileSingleMsgAESITBNoMACV1, false},
			{triple.ProfileSingleMsgAESITBMACV1, false},
			{triple.ProfileStreamingAEADAESITBMACV1, true},
			{triple.ProfileStreamingNoAEADAESITBV1, true},
		} {
			t.Run(fmt.Sprintf("%s/nb%d", tc.profile, nb), func(t *testing.T) {
				opts := triple.Opts{NonceBits: nb}
				var pX8 *triple.Pipeline
				var blob []byte
				var err error
				withX8Arm(t, true, func() { pX8, blob, err = triple.Init(tc.profile, opts) })
				if err != nil {
					t.Fatalf("Init(x8): %v", err)
				}
				defer pX8.Close()
				var pX4 *triple.Pipeline
				withX8Arm(t, false, func() { pX4, err = triple.Load(blob) })
				if err != nil {
					t.Fatalf("Load(x4): %v", err)
				}
				defer pX4.Close()
				run := func(enc, dec *triple.Pipeline) {
					var wire, got []byte
					var err error
					if tc.streaming {
						wire, err = enc.EncryptStreamBytes(plain)
					} else {
						wire, err = enc.EncryptMessage(plain)
					}
					if err != nil {
						t.Fatalf("encrypt: %v", err)
					}
					if tc.streaming {
						got, err = dec.DecryptStreamBytes(wire)
					} else {
						got, err = dec.DecryptMessage(wire)
					}
					if err != nil || !bytes.Equal(got, plain) {
						t.Fatalf("decrypt: err=%v match=%v", err, bytes.Equal(got, plain))
					}
				}
				run(pX8, pX4)
				run(pX4, pX8)
			})
		}
	}
}

// TestAESITBFusedX8LowLevelRoundTrip drives the Low-Level Encrypt3x128Cfg
// / Decrypt3x128Cfg entry points with seeds built through the Low-Level
// helper: the eight-lane hook is attached there as well, and a message
// encrypted with the hook decrypts through seeds rebuilt from the same
// components without it. Every nonce width and odd pixel counts, so the
// eight-, four- and single-pixel tails are all exercised.
func TestAESITBFusedX8LowLevelRoundTrip(t *testing.T) {
	x8Hosted(t)
	build := func(armed bool, keys [][]byte, comps [][]uint64) [8]*itb.Seed128 {
		var out [8]*itb.Seed128
		withX8Arm(t, armed, func() {
			for i := range out {
				if comps == nil {
					out[i], keys[i] = newAESITBSeed(t, 512, nil)
				} else {
					out[i] = aesitbSeedFromComponents(t, keys[i], comps[i])
				}
				if (out[i].BatchFusedChain8() != nil) != armed {
					t.Fatalf("seed %d: eight-lane hook presence %v, want %v", i, out[i].BatchFusedChain8() != nil, armed)
				}
			}
		})
		return out
	}
	keys := make([][]byte, 8)
	x8 := build(true, keys, nil)
	comps := make([][]uint64, 8)
	for i := range comps {
		comps[i] = append([]uint64(nil), x8[i].Components...)
	}
	x4 := build(false, keys, comps)
	for _, nb := range []int{128, 256, 512} {
		cfg := &itb.Config{NonceBits: nb}
		for _, size := range []int{1, 77, 4093, 65_537} {
			plain := make([]byte, size)
			rand.Read(plain)
			wire, err := itb.Encrypt3x128Cfg(cfg, x8[0], x8[1], x8[2], x8[3], x8[4], x8[5], x8[6], x8[7], plain)
			if err != nil {
				t.Fatalf("nb=%d size=%d encrypt(x8): %v", nb, size, err)
			}
			got, err := itb.Decrypt3x128Cfg(cfg, x4[0], x4[1], x4[2], x4[3], x4[4], x4[5], x4[6], x4[7], wire)
			if err != nil || !bytes.Equal(got, plain) {
				t.Fatalf("nb=%d size=%d decrypt(x4): err=%v match=%v", nb, size, err, bytes.Equal(got, plain))
			}
			wire, err = itb.Encrypt3x128Cfg(cfg, x4[0], x4[1], x4[2], x4[3], x4[4], x4[5], x4[6], x4[7], plain)
			if err != nil {
				t.Fatalf("nb=%d size=%d encrypt(x4): %v", nb, size, err)
			}
			got, err = itb.Decrypt3x128Cfg(cfg, x8[0], x8[1], x8[2], x8[3], x8[4], x8[5], x8[6], x8[7], wire)
			if err != nil || !bytes.Equal(got, plain) {
				t.Fatalf("nb=%d size=%d decrypt(x8): err=%v match=%v", nb, size, err, bytes.Equal(got, plain))
			}
		}
	}
}

// --- Triple Ouroboros integration benchmarks ---

// Triple Ouroboros (8-seed) integration benchmarks for the aesitb128
// primitive, driving the Encrypt3x128Cfg / Decrypt3x128Cfg entry points
// in the same shape as the other primitives' cells in itb3_ext_test.go
// (BenchmarkExtTriple<Primitive>_<KeyBits>bit_<Direction>_<Size>MB), so
// the BENCH3.md mask `BenchmarkExtTriple.*_(1MB|16MB|64MB)$` picks the
// cells up alongside every other registry primitive.
//
// The generic bench{Encrypt,Decrypt}3x128CachedBatchedExt drivers wire
// only the (Hash, BatchHash) pair per seed. The shipping aesitb128 path
// additionally carries the fused ChainHash cascade hooks (FusedChain /
// BatchFusedChain) that the triple package installs through
// hashes.NewSeed128 at Init time; without them the Low-Level entry
// points fall back to the sequential per-round cascade. The drivers
// below therefore build each of the eight seeds through the same
// constructor, so the cells measure the path the Triple pipeline runs.

// newAESITB128SeedExt returns one independently-keyed aesitb128 seed at
// the given ITB width with the single, batched, fused-cascade and
// batch-16 interlock fill hooks attached — the same wiring the triple
// package performs per slot.
func newAESITB128SeedExt(b *testing.B, bits int) *itb.Seed128 {
	b.Helper()
	s, _, err := hashes.NewSeed128(hashes.CipherAESITB128, bits)
	if err != nil {
		b.Fatal(err)
	}
	return s
}

// makeEightAESITB128SeedsExt builds the eight-seed constellation
// (noise + lockSeed + 3 data + 3 start), each slot on its own fixed key.
func makeEightAESITB128SeedsExt(b *testing.B, bits int) (ns, ls, ds1, ds2, ds3, ss1, ss2, ss3 *itb.Seed128) {
	b.Helper()
	ns = newAESITB128SeedExt(b, bits)
	ls = newAESITB128SeedExt(b, bits)
	ds1 = newAESITB128SeedExt(b, bits)
	ds2 = newAESITB128SeedExt(b, bits)
	ds3 = newAESITB128SeedExt(b, bits)
	ss1 = newAESITB128SeedExt(b, bits)
	ss2 = newAESITB128SeedExt(b, bits)
	ss3 = newAESITB128SeedExt(b, bits)
	return
}

// benchEncrypt3x128AESITBExt mirrors benchEncrypt3x128CachedBatchedExt
// with the fused-cascade hooks attached on every seed.
func benchEncrypt3x128AESITBExt(b *testing.B, bits, dataSize int) {
	ns, ls, ds1, ds2, ds3, ss1, ss2, ss3 := makeEightAESITB128SeedsExt(b, bits)
	data := generateDataExt(dataSize)
	cfg := extTripleBenchCfg()
	b.SetBytes(int64(dataSize))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = itb.Encrypt3x128Cfg(cfg, ns, ls, ds1, ds2, ds3, ss1, ss2, ss3, data)
	}
}

// benchDecrypt3x128AESITBExt mirrors benchDecrypt3x128CachedBatchedExt
// with the fused-cascade hooks attached on every seed.
func benchDecrypt3x128AESITBExt(b *testing.B, bits, dataSize int) {
	ns, ls, ds1, ds2, ds3, ss1, ss2, ss3 := makeEightAESITB128SeedsExt(b, bits)
	data := generateDataExt(dataSize)
	cfg := extTripleBenchCfg()
	encrypted, err := itb.Encrypt3x128Cfg(cfg, ns, ls, ds1, ds2, ds3, ss1, ss2, ss3, data)
	if err != nil {
		b.Fatal(err)
	}
	// Verify the round trip once before timing so a forced dispatch
	// tier that produced garbage cannot report a throughput number.
	if back, err := itb.Decrypt3x128Cfg(cfg, ns, ls, ds1, ds2, ds3, ss1, ss2, ss3, encrypted); err != nil {
		b.Fatal(err)
	} else if !bytes.Equal(back, data) {
		b.Fatal("decrypt round trip mismatch")
	}
	b.SetBytes(int64(dataSize))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = itb.Decrypt3x128Cfg(cfg, ns, ls, ds1, ds2, ds3, ss1, ss2, ss3, encrypted)
	}
}

// --- AES-ITB-128 Triple Pair benches: 512-bit ITB width ---

func BenchmarkExtTripleAESITB128_512bit_Encrypt_1MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 512, 1<<20)
}
func BenchmarkExtTripleAESITB128_512bit_Encrypt_16MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 512, 16<<20)
}
func BenchmarkExtTripleAESITB128_512bit_Encrypt_64MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 512, 64<<20)
}
func BenchmarkExtTripleAESITB128_512bit_Decrypt_1MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 512, 1<<20)
}
func BenchmarkExtTripleAESITB128_512bit_Decrypt_16MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 512, 16<<20)
}
func BenchmarkExtTripleAESITB128_512bit_Decrypt_64MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 512, 64<<20)
}

// --- AES-ITB-128 Triple Pair benches: 1024-bit ITB width ---

func BenchmarkExtTripleAESITB128_1024bit_Encrypt_1MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 1024, 1<<20)
}
func BenchmarkExtTripleAESITB128_1024bit_Encrypt_16MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 1024, 16<<20)
}
func BenchmarkExtTripleAESITB128_1024bit_Encrypt_64MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 1024, 64<<20)
}
func BenchmarkExtTripleAESITB128_1024bit_Decrypt_1MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 1024, 1<<20)
}
func BenchmarkExtTripleAESITB128_1024bit_Decrypt_16MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 1024, 16<<20)
}
func BenchmarkExtTripleAESITB128_1024bit_Decrypt_64MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 1024, 64<<20)
}

// --- AES-ITB-128 Triple Pair benches: 2048-bit ITB width ---

func BenchmarkExtTripleAESITB128_2048bit_Encrypt_1MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 2048, 1<<20)
}
func BenchmarkExtTripleAESITB128_2048bit_Encrypt_16MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 2048, 16<<20)
}
func BenchmarkExtTripleAESITB128_2048bit_Encrypt_64MB(b *testing.B) {
	benchEncrypt3x128AESITBExt(b, 2048, 64<<20)
}
func BenchmarkExtTripleAESITB128_2048bit_Decrypt_1MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 2048, 1<<20)
}
func BenchmarkExtTripleAESITB128_2048bit_Decrypt_16MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 2048, 16<<20)
}
func BenchmarkExtTripleAESITB128_2048bit_Decrypt_64MB(b *testing.B) {
	benchDecrypt3x128AESITBExt(b, 2048, 64<<20)
}

// --- Pipeline profile benchmarks ---

// benchMaxWorkers returns the ITB_MAX_WORKERS override for bench cells
// that pin the pipeline's worker cap. Zero (the return when the env
// var is unset, empty, non-numeric, or negative) leaves the pipeline
// at the [runtime.NumCPU] default; a positive integer clamps every
// cell to that worker count, so cross-host bench cells can be timed
// under an identical worker cap.
func benchMaxWorkers() int {
	v := os.Getenv("ITB_MAX_WORKERS")
	if v == "" {
		return 0
	}
	n, err := strconv.Atoi(v)
	if err != nil || n < 0 {
		return 0
	}
	return n
}

// benchInterlockGeometry applies ITB_BENCH_UNRANK8X2=1: the 16-chunk
// interlock superblock runs as two 8-lane kernel passes instead of the
// 16-lane kernel, so both geometries can be timed from one binary.
func benchInterlockGeometry(b *testing.B) {
	if os.Getenv("ITB_BENCH_UNRANK8X2") == "1" {
		saved := interlock.UseUnrank16
		interlock.UseUnrank16 = false
		b.Cleanup(func() { interlock.UseUnrank16 = saved })
	}
}

// BenchmarkExtWorkersAESITB128 drives every shipped AES-ITB profile
// (InnerHash aesitb128, wrapper and parallax off) through its mode's
// encrypt / decrypt surface at 64 MB, at 512-, 1024- and 2048-bit
// keys (5 / 9 / 17 cascade rounds in the batch-16 Interlocked Barrier
// fill hot loop), once through the fused ChainHash cascade kernel and
// once through the sequential per-round loop
// (ITB_FORCE_CHAINHASH_SEQ=1 at Init time). Every cell shares the same
// worker cap: ITB_MAX_WORKERS pins the pipeline to a specific worker
// count when set, and leaves the pipeline at the [runtime.NumCPU]
// default when unset — cross-host cells can be compared under an
// identical cap by exporting the same value on every host. The
// standard 1 / 16 / 64 MB message-size sweep for aesitb128 lives in
// this file's Triple Ouroboros integration cells.
func BenchmarkExtWorkersAESITB128(b *testing.B) {
	benchInterlockGeometry(b)
	workers := benchMaxWorkers()
	const size = 64 << 20
	plain := make([]byte, size)
	rand.Read(plain)
	profiles := []struct {
		name      string
		profile   string
		streaming bool
	}{
		{"singlemsg-mac", triple.ProfileSingleMsgAESITBMACV1, false},
		{"singlemsg-nomac", triple.ProfileSingleMsgAESITBNoMACV1, false},
		{"streaming-aead-mac", triple.ProfileStreamingAEADAESITBMACV1, true},
		{"streaming-noaead", triple.ProfileStreamingNoAEADAESITBV1, true},
	}
	for _, keyBits := range []int{512, 1024, 2048} {
		for _, path := range []string{"fused", "seq"} {
			for _, tc := range profiles {
				if path == "seq" {
					os.Setenv("ITB_FORCE_CHAINHASH_SEQ", "1")
				}
				p, _, err := triple.Init(tc.profile, triple.Opts{KeyBits: keyBits})
				os.Unsetenv("ITB_FORCE_CHAINHASH_SEQ")
				if err != nil {
					b.Fatal(err)
				}
				p.MaxWorkers(workers)
				enc := p.EncryptMessage
				dec := p.DecryptMessage
				if tc.streaming {
					enc = p.EncryptStreamBytes
					dec = p.DecryptStreamBytes
				}
				wire, err := enc(plain)
				if err != nil {
					b.Fatal(err)
				}
				label := fmt.Sprintf("%s/%dbit/%s", tc.name, keyBits, path)
				b.Run(fmt.Sprintf("%s/Encrypt_64MB", label), func(b *testing.B) {
					b.SetBytes(size)
					b.ReportAllocs()
					for i := 0; i < b.N; i++ {
						if _, err := enc(plain); err != nil {
							b.Fatal(err)
						}
					}
				})
				b.Run(fmt.Sprintf("%s/Decrypt_64MB", label), func(b *testing.B) {
					b.SetBytes(size)
					b.ReportAllocs()
					for i := 0; i < b.N; i++ {
						if _, err := dec(wire); err != nil {
							b.Fatal(err)
						}
					}
				})
				p.Close()
			}
		}
	}
}

// BenchmarkAESITBProfileCell builds exactly one AES-ITB pipeline — chosen
// through ITB_BENCH_PROFILE (singlemsg-mac | singlemsg-nomac |
// streaming-aead-mac | streaming-noaead, default singlemsg-nomac),
// ITB_BENCH_KEYBITS (default 512) and ITB_BENCH_PATH (fused | seq,
// default fused) — and times its Encrypt / Decrypt at 64 MB. The worker
// cap follows ITB_MAX_WORKERS when set and defaults to [runtime.NumCPU]
// otherwise. Intended for -cpuprofile runs: nothing but the selected
// cell's pipeline exists in the process, so the profile carries no
// setup work from other cells.
func BenchmarkAESITBProfileCell(b *testing.B) {
	benchInterlockGeometry(b)
	const size = 64 << 20
	profiles := map[string]struct {
		profile   string
		streaming bool
	}{
		"singlemsg-mac":      {triple.ProfileSingleMsgAESITBMACV1, false},
		"singlemsg-nomac":    {triple.ProfileSingleMsgAESITBNoMACV1, false},
		"streaming-aead-mac": {triple.ProfileStreamingAEADAESITBMACV1, true},
		"streaming-noaead":   {triple.ProfileStreamingNoAEADAESITBV1, true},
	}
	name := os.Getenv("ITB_BENCH_PROFILE")
	if name == "" {
		name = "singlemsg-nomac"
	}
	tc, ok := profiles[name]
	if !ok {
		b.Fatalf("ITB_BENCH_PROFILE=%q unknown", name)
	}
	keyBits := 512
	if v := os.Getenv("ITB_BENCH_KEYBITS"); v != "" {
		if _, err := fmt.Sscanf(v, "%d", &keyBits); err != nil {
			b.Fatal(err)
		}
	}
	if os.Getenv("ITB_BENCH_PATH") == "seq" {
		os.Setenv("ITB_FORCE_CHAINHASH_SEQ", "1")
	}
	p, _, err := triple.Init(tc.profile, triple.Opts{KeyBits: keyBits})
	os.Unsetenv("ITB_FORCE_CHAINHASH_SEQ")
	if err != nil {
		b.Fatal(err)
	}
	p.MaxWorkers(benchMaxWorkers())
	defer p.Close()
	plain := make([]byte, size)
	rand.Read(plain)
	enc := p.EncryptMessage
	dec := p.DecryptMessage
	if tc.streaming {
		enc = p.EncryptStreamBytes
		dec = p.DecryptStreamBytes
	}
	wire, err := enc(plain)
	if err != nil {
		b.Fatal(err)
	}
	b.Run("Encrypt", func(b *testing.B) {
		b.SetBytes(size)
		b.ReportAllocs()
		for i := 0; i < b.N; i++ {
			if _, err := enc(plain); err != nil {
				b.Fatal(err)
			}
		}
	})
	b.Run("Decrypt", func(b *testing.B) {
		b.SetBytes(size)
		b.ReportAllocs()
		for i := 0; i < b.N; i++ {
			if _, err := dec(wire); err != nil {
				b.Fatal(err)
			}
		}
	})
}
