// External-test-package helpers shared with itb3_ext_test.go. Both
// files live in `package itb_test` so cross-file symbol reuse is free;
// this file carries only the helper functions (seed builders, primitive
// Pair factories, LockSeed-attach fixtures), and the Triple Ouroboros
// benchmarks + integration tests live in itb3_ext_test.go.
package itb_test

import (
	"crypto/rand"
	"testing"

	"github.com/everanium/itb"
	"github.com/everanium/itb/hashes"
)

// --- Seed builders ----------------------------------------------------------

// makeTripleSeed128Ext constructs the three ITB seeds (noise, data,
// start) for the Single Message shape at 128-bit hash width. All three
// seeds bind to the same hash function; per-seed component material is
// CSPRNG-generated by NewSeed128.
func makeTripleSeed128Ext(bits int, h itb.HashFunc128) (noise, data, start *itb.Seed128) {
	noise, _ = itb.NewSeed128(bits, h)
	data, _ = itb.NewSeed128(bits, h)
	start, _ = itb.NewSeed128(bits, h)
	return
}

// makeTripleSeed256Ext — 256-bit counterpart of makeTripleSeed128Ext.
func makeTripleSeed256Ext(bits int, h itb.HashFunc256) (noise, data, start *itb.Seed256) {
	noise, _ = itb.NewSeed256(bits, h)
	data, _ = itb.NewSeed256(bits, h)
	start, _ = itb.NewSeed256(bits, h)
	return
}

// makeTripleSeed512Ext — 512-bit counterpart of makeTripleSeed128Ext.
func makeTripleSeed512Ext(bits int, h itb.HashFunc512) (noise, data, start *itb.Seed512) {
	noise, _ = itb.NewSeed512(bits, h)
	data, _ = itb.NewSeed512(bits, h)
	start, _ = itb.NewSeed512(bits, h)
	return
}

// generateDataExt returns n bytes of cryptographically random data
// suitable for use as plaintext or fixture input.
func generateDataExt(n int) []byte {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	return b
}

// --- Primitive Pair factories -----------------------------------------------
//
// Each returns the (single-call, batched) hash pair for the named
// primitive at the corresponding ITB seed width. Every fresh call to a
// Pair() constructor produces an independently-keyed hasher — callers
// building multiple seeds under one primitive should share the pair
// across those seeds if they want identical hash state, or call the
// factory once per seed for independent keys.

func makeBlake2bHash256PairExt() (itb.HashFunc256, itb.BatchHashFunc256) {
	h, b, _ := hashes.BLAKE2b256Pair()
	return h, b
}

func makeBlake2bHash512PairExt() (itb.HashFunc512, itb.BatchHashFunc512) {
	h, b, _ := hashes.BLAKE2b512Pair()
	return h, b
}

func makeBlake2sHash256PairExt() (itb.HashFunc256, itb.BatchHashFunc256) {
	h, b, _ := hashes.BLAKE2s256Pair()
	return h, b
}

func makeBlake3Hash256PairExt() (itb.HashFunc256, itb.BatchHashFunc256) {
	h, b, _ := hashes.BLAKE3256Pair()
	return h, b
}

func makeChaCha20Hash256PairExt() (itb.HashFunc256, itb.BatchHashFunc256) {
	h, b, _ := hashes.ChaCha20256Pair()
	return h, b
}

func makeAESCMACHash128PairExt() (itb.HashFunc128, itb.BatchHashFunc128) {
	h, b, _ := hashes.AESCMACPair()
	return h, b
}

func makeSipHash24Hash128PairExt() (itb.HashFunc128, itb.BatchHashFunc128) {
	h, b := hashes.SipHash24Pair()
	return h, b
}

func makeAreion256Hash256PairExt() (itb.HashFunc256, itb.BatchHashFunc256) {
	h, b, _ := hashes.Areion256Pair()
	return h, b
}

func makeAreion512Hash512PairExt() (itb.HashFunc512, itb.BatchHashFunc512) {
	h, b, _ := hashes.Areion512Pair()
	return h, b
}

// --- LockSeed-attach fixtures -----------------------------------------------
//
// The AttachLockSeed pattern installs a dedicated lockSeed as the
// bit-permutation entropy source for the overlay path. These helpers
// build fresh Seed{128,256,512} instances suitable for use as either
// the noiseSeed or the attached lockSeed; each call yields an
// independently-keyed hasher via the corresponding Pair factory.

func makeBlake3SeedAttachExt(t *testing.T, bits int) *itb.Seed256 {
	t.Helper()
	h, b, _ := hashes.BLAKE3256Pair()
	s, err := itb.NewSeed256(bits, h)
	if err != nil {
		t.Fatalf("NewSeed256(%d): %v", bits, err)
	}
	s.BatchHash = b
	return s
}

func makeSipHash128SeedAttachExt(t *testing.T, bits int) *itb.Seed128 {
	t.Helper()
	h, b := hashes.SipHash24Pair()
	s, err := itb.NewSeed128(bits, h)
	if err != nil {
		t.Fatalf("NewSeed128(%d): %v", bits, err)
	}
	s.BatchHash = b
	return s
}

func makeBlake2b512SeedAttachExt(t *testing.T, bits int) *itb.Seed512 {
	t.Helper()
	h, b, _ := hashes.BLAKE2b512Pair()
	s, err := itb.NewSeed512(bits, h)
	if err != nil {
		t.Fatalf("NewSeed512(%d): %v", bits, err)
	}
	s.BatchHash = b
	return s
}

// withLockSoupAttachExt enables SetLockSoup(1) for the duration of the
// test, restoring the previous LockSoup state via t.Cleanup. The
// bit-permutation overlay must be on for AttachLockSeed to have an
// observable effect on the wire output.
func withLockSoupAttachExt(t *testing.T) {
	t.Helper()
	prevLS := itb.GetLockSoup()
	itb.SetLockSoup(1)
	t.Cleanup(func() {
		itb.SetLockSoup(prevLS)
	})
}
