<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Everanium.Itb.VisualBasic.Eitb</RootNamespace>
    <AssemblyName>EveraniumItb.VisualBasic.Eitb</AssemblyName>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EveraniumItb.VisualBasic\EveraniumItb.VisualBasic.vbproj" />
  </ItemGroup>

</Project>
