// Generator for the fully-unrolled AVX-512 (EVEX 128-bit) Keccak-f[1600]
// permutation kernel at macs/internal/keccakasm/keccakf_amd64.s.
//
// Layout: one lane per XMM register (lane L = x + 5*y -> initially X_L),
// 25 lanes in X0..X24, chi temporaries rotate through the remaining
// registers, X30/X31 permanent scratch. Pi is register renaming (zero
// instructions); the generator tracks the lane->register map across the
// 24 rounds and emits the final stores from wherever the lanes ended up.
//
// Two entry points are emitted from the same round body: the plain
// permutation and a fused rate-block absorb (XOR 136 message bytes into
// lanes 0..16 during the state load, then permute).
//
// Run from the repository root:
//
//	go run ./scripts/kernels/macs/keccakasm > macs/internal/keccakasm/keccakf_amd64.s
//
// The emitter is deterministic: regenerating without source changes
// reproduces the committed kernel byte for byte.
package main

import (
	"fmt"
	"strings"
)

var rc = [24]uint64{
	0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000,
	0x000000000000808B, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
	0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
	0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003,
	0x8000000000008002, 0x8000000000000080, 0x000000000000800A, 0x800000008000000A,
	0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008,
}

// rot[x][y] — Keccak rho rotation offsets.
var rot = [5][5]int{
	{0, 36, 3, 41, 18},
	{1, 44, 10, 45, 2},
	{62, 6, 43, 15, 61},
	{28, 55, 25, 21, 56},
	{27, 20, 39, 8, 14},
}

func x(r int) string { return fmt.Sprintf("X%d", r) }

func main() {
	var b strings.Builder
	emit := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	emit("//go:build amd64 && !purego && !noitbasm")
	emit("")
	emit("// AVX-512 (EVEX 128-bit, AVX512F + AVX512VL) Keccak-f[1600] permutation.")
	emit("//")
	emit("// Code generated by a deterministic emitter; the construction is described")
	emit("// in the package documentation (keccakasm_amd64.go). DO NOT EDIT by hand —")
	emit("// regenerate instead.")
	emit("//")
	emit("// Layout: one 64-bit lane per XMM register. Lane L = x + 5*y starts in")
	emit("// X_L (X0..X24); X25..X29 hold theta parity / chi temporaries; X30/X31")
	emit("// are scratch. Pi is pure register renaming: no shuffle instructions are")
	emit("// emitted, the lane->register assignment rotates across the fully")
	emit("// unrolled 24 rounds and the epilogue stores each lane from its final")
	emit("// register. Per round:")
	emit("//")
	emit("//   theta:  C[x] via VPXORQ + VPTERNLOGQ $0x96 + VPXORQ (5-way XOR in 3")
	emit("//           ops, no copies), D[x] = C[x-1] ^ rol1(C[x+1]) via")
	emit("//           VPROLQ $1 + VPXORQ, then 25 VPXORQ lane updates.")
	emit("//   rho:    24 immediate VPROLQ (lane (0,0) has offset 0).")
	emit("//   pi:     free (register renaming).")
	emit("//   chi:    per lane VMOVDQA64 (rename-eliminated) + VPTERNLOGQ $0xD2")
	emit("//           (a ^ (~b & c)) — 25 ternlog folds per round.")
	emit("//   iota:   one VPXORQ.BCST from the round-constant table at a fixed")
	emit("//           public offset.")
	emit("//")
	emit("// Constant-time: no branches, no data-dependent addressing; every memory")
	emit("// access is the state array / rate block at fixed offsets plus the public")
	emit("// RC table.")
	emit("")
	emit("#include \"textflag.h\"")
	emit("")
	for i, c := range rc {
		emit("DATA keccakRC<>+0x%02x(SB)/8, $0x%016X", i*8, c)
	}
	emit("GLOBL keccakRC<>(SB), RODATA|NOPTR, $192")

	body := func(fused bool) {
		emit("")
		if fused {
			emit("// func keccakAbsorb136AVX512(a *[25]uint64, block *byte)")
			emit("//")
			emit("// Fused absorb: XORs one 136-byte rate block into lanes 0..16 while")
			emit("// the state streams into registers, then applies the permutation —")
			emit("// one state load/store round-trip per block instead of two.")
			emit("TEXT ·keccakAbsorb136AVX512(SB), NOSPLIT, $0-16")
		} else {
			emit("// func keccakF1600AVX512(a *[25]uint64)")
			emit("TEXT ·keccakF1600AVX512(SB), NOSPLIT, $0-8")
		}
		emit("\tMOVQ a+0(FP), DI")
		if fused {
			emit("\tMOVQ block+8(FP), SI")
		}
		emit("\tLEAQ keccakRC<>(SB), AX")
		emit("")

		// lane -> register number
		m := [25]int{}
		for l := 0; l < 25; l++ {
			m[l] = l
			emit("\tVMOVQ %d(DI), %s", l*8, x(l))
			if fused && l < 17 {
				emit("\tVMOVQ %d(SI), X31", l*8)
				emit("\tVPXORQ X31, %s, %s", x(l), x(l))
			}
		}
		free := []int{25, 26, 27, 28, 29}
		const scratch = 30

		for round := 0; round < 24; round++ {
			emit("")
			emit("\t// ---- round %d ----", round)
			// theta: C[x] in free[x]
			C := [5]int{}
			emit("\t// theta: column parities")
			for cx := 0; cx < 5; cx++ {
				C[cx] = free[cx]
				emit("\tVPXORQ %s, %s, %s", x(m[cx+5]), x(m[cx]), x(C[cx]))
				emit("\tVPTERNLOGQ $0x96, %s, %s, %s", x(m[cx+15]), x(m[cx+10]), x(C[cx]))
				emit("\tVPXORQ %s, %s, %s", x(m[cx+20]), x(C[cx]), x(C[cx]))
			}
			emit("\t// theta: D[x] = C[x-1] ^ rol1(C[x+1]); lane updates")
			for cx := 0; cx < 5; cx++ {
				emit("\tVPROLQ $1, %s, %s", x(C[(cx+1)%5]), x(scratch))
				emit("\tVPXORQ %s, %s, %s", x(C[(cx+4)%5]), x(scratch), x(scratch))
				for y := 0; y < 5; y++ {
					l := cx + 5*y
					emit("\tVPXORQ %s, %s, %s", x(scratch), x(m[l]), x(m[l]))
				}
			}
			// rho
			emit("\t// rho: fixed-offset lane rotations")
			for l := 0; l < 25; l++ {
				r := rot[l%5][l/5]
				if r != 0 {
					emit("\tVPROLQ $%d, %s, %s", r, x(m[l]), x(m[l]))
				}
			}
			// pi + chi
			emit("\t// pi (register renaming) + chi (VPTERNLOGQ $0xD2 per lane)")
			var newm [25]int
			for j := 0; j < 5; j++ {
				var srcs [5]int
				for i := 0; i < 5; i++ {
					srcs[i] = m[(i+3*j)%5+5*i]
				}
				temps := free
				for i := 0; i < 5; i++ {
					emit("\tVMOVDQA64 %s, %s", x(srcs[i]), x(temps[i]))
					emit("\tVPTERNLOGQ $0xD2, %s, %s, %s",
						x(srcs[(i+2)%5]), x(srcs[(i+1)%5]), x(temps[i]))
					newm[i+5*j] = temps[i]
				}
				free = append([]int(nil), srcs[:]...)
			}
			m = newm
			// iota
			emit("\t// iota: RC[%d]", round)
			emit("\tVPXORQ.BCST %d(AX), %s, %s", round*8, x(m[0]), x(m[0]))
		}

		emit("")
		for l := 0; l < 25; l++ {
			emit("\tVMOVQ %s, %d(DI)", x(m[l]), l*8)
		}
		emit("\tVZEROUPPER")
		emit("\tRET")
	}

	body(false)
	body(true)

	fmt.Print(b.String())
}
